# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  apiuser:
    image: apiuser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80
    depends_on:
      - db

  db:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433